import Footer from './components/Footer';
import NavBar from './components/NavBar';
import TopNav from './components/TopNav';
import './globals.css';
import {
  Inter,
  Lobster_Two,
  Prompt,
  Gelasio,
  Luckiest_Guy,
} from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const prompt = Prompt({
  weight: ['700', '500'],
  subsets: ['latin'],
  variable: '--font-prompt',
});

const luckiest = Luckiest_Guy({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-luckiest',
});

const gelasio = Gelasio({
  weight: ['700', '500'],
  subsets: ['latin'],
  variable: '--font-gelasio',
});

export const metadata = {
  title: 'R&S TOWING',
  description: 'Generated by create next app',
};

const lobster = Lobster_Two({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-lobster',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${prompt.variable}  ${lobster.variable} ${gelasio.variable} ${luckiest.variable}`}
      >
        <TopNav />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
